controller_manager:
  ros__parameters:
    # update_rate: 250  # Hz
    update_rate: 100  # Hz
    # update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    youbot_arm_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"


youbot_arm_controller:
  ros__parameters:
    joints:
      - youbot_arm_joint_1
      - youbot_arm_joint_2
      - youbot_arm_joint_3
      - youbot_arm_joint_4
      - youbot_arm_joint_5

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    # open_loop_control: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      youbot_arm_joint_1:
        trajectory: 0.05
        goal: 0.03
      youbot_arm_joint_2:
        trajectory: 0.05
        goal: 0.03
      youbot_arm_joint_3:
        trajectory: 0.05
        goal: 0.03
      youbot_arm_joint_4:
        trajectory: 0.05
        goal: 0.03
      youbot_arm_joint_5:
        trajectory: 0.05
        goal: 0.03