controller_manager:
  ros__parameters:
    # update_rate: 250  # Hz
    update_rate: 100  # Hz
    # update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    # forward_velocity_controller:
    #   type: forward_command_controller/ForwardCommandController

# joint_state_broadcaster:
#   ros__parameters:
#     joints:
#       - joint_0
#       - joint_1
#       - joint_2
#       - joint_3
#       - joint_4
#     interfaces:
#       - position
#       - velocity
#       - effort

# forward_velocity_controller:
#   ros__parameters:
#     joints:
#       - arm_joint_1
#       - arm_joint_2
#       - arm_joint_3
#       - arm_joint_4
#       - arm_joint_5
#     interface_name: velocity

joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    # open_loop_control: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      arm_joint_1:
        trajectory: 0.05
        goal: 0.03
      arm_joint_2:
        trajectory: 0.05
        goal: 0.03
      arm_joint_3:
        trajectory: 0.05
        goal: 0.03
      arm_joint_4:
        trajectory: 0.05
        goal: 0.03
      arm_joint_5:
        trajectory: 0.05
        goal: 0.03