controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

# joint_state_broadcaster:
#   ros__parameters:
#     joints:
#       - joint_0
#       - joint_1
#       - joint_2
#       - joint_3
#       - joint_4
#     interfaces:
#       - position
#       - velocity
#       - effort

forward_velocity_controller:
  ros__parameters:
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    interface_name: velocity

